name:                learn-haskell
version:             0.1.0.0

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  learn-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - learn-haskell
    - hspec
